import { connectFirebase } from "./firebase-store.js";

const COLORS=["#ef476f","#118ab2","#06a77d","#7b61ff","#f08c46","#9c528b","#4d7c0f","#475569"];
const STATUS={interested:["🤔","Interested"],dated:["🗓","Considering"],booked:["🎟","Booked"],seen:["✓","Seen"]};
const KEY="fringe-friends-2026";
const state={shows:[],visible:40,view:"shows",selectedDate:"all",undo:null,...loadState()};
let remoteStore=null;
let canonicalShowIds=new Map;
const $=id=>document.getElementById(id);
const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function defaults(){return{people:[{id:crypto.randomUUID(),name:"Daniel",initials:"DS",colour:COLORS[1]}],plans:[],activity:[],currentPersonId:null,recentAttendees:[]}}
function loadState(){try{return{...defaults(),...JSON.parse(localStorage.getItem(KEY))}}catch{return defaults()}}
function sharedSnapshot(){return{people:state.people,plans:state.plans,activity:state.activity}}
function persist(sync=true){localStorage.setItem(KEY,JSON.stringify({...sharedSnapshot(),currentPersonId:state.currentPersonId,recentAttendees:state.recentAttendees}));if(sync&&remoteStore)remoteStore.sync(sharedSnapshot()).catch(showSyncError)}
function showSyncError(error){console.error(error);$("snackbarText").textContent="Could not synchronise changes";$("undoButton").hidden=true;$("snackbar").classList.add("show");clearTimeout(undoTimer);undoTimer=setTimeout(()=>{$("undoButton").hidden=false;hideSnack()},7000)}
function consolidatePlans(plans){const buckets=new Map;for(const plan of plans){const key=JSON.stringify([plan.showId,plan.status,plan.date]);const bucket=buckets.get(key)||[];bucket.push(structuredClone(plan));buckets.set(key,bucket)}const merged=[];for(const bucket of buckets.values()){const timed=new Map,untimed=[];for(const plan of bucket){if(plan.time){const existing=timed.get(plan.time);if(existing)mergeAttendance(existing,plan);else timed.set(plan.time,plan)}else untimed.push(plan)}if(timed.size===1){const target=[...timed.values()][0];untimed.forEach(plan=>mergeAttendance(target,plan))}else if(untimed.length){const target=untimed.shift();untimed.forEach(plan=>mergeAttendance(target,plan));merged.push(target)}merged.push(...timed.values())}return merged}
function mergeAttendance(target,source){target.attendeeIds=[...new Set([...target.attendeeIds,...source.attendeeIds])].sort();if(!target.time&&source.time)target.time=source.time;if(String(source.updatedAt)>String(target.updatedAt)){target.updatedAt=source.updatedAt;target.updatedBy=source.updatedBy}}
function normaliseTitle(value){return String(value??"").normalize("NFKC").replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[–—]/g,"-").replace(/\s+/g," ").trim().toLocaleLowerCase("en-GB")}
function canonicaliseCatalogue(shows){canonicalShowIds=new Map;const unique=new Map;for(const showItem of shows){const key=normaliseTitle(showItem.title);if(!unique.has(key))unique.set(key,showItem);canonicalShowIds.set(showItem.id,unique.get(key).id)}return [...unique.values()]}
function canonicalisePlans(plans){return consolidatePlans(plans.map(plan=>({...plan,showId:canonicalShowIds.get(plan.showId)||plan.showId})))}
function applyRemote(data){state.people=data.people;state.plans=canonicalisePlans(data.plans);state.activity=data.activity;if(!person(state.currentPersonId))state.currentPersonId=state.people[0]?.id??null;persist(Boolean(remoteStore));renderAll()}
function person(id){return state.people.find(p=>p.id===id)}
function show(id){return state.shows.find(s=>s.id===id)||{id,title:"Unknown show"}}
function current(){return person(state.currentPersonId)}
function initials(p){return `<span class="avatar" title="${esc(p.name)}" style="background:${p.colour}">${esc(p.initials)}</span>`}
function attendeeAvatars(ids=[]){return `<span class="avatars">${ids.map(id=>person(id)).filter(Boolean).map(initials).join("")}</span>`}
function effectiveStatus(plan){if(plan.status==="booked"&&plan.date&&plan.date<todayIso())return "seen";return plan.status}
function todayIso(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function dateLabel(iso){if(!iso)return "";return new Date(`${iso}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}
function planLine(plan){const status=effectiveStatus(plan),[icon,label]=STATUS[status];const when=[plan.date&&dateLabel(plan.date),plan.time].filter(Boolean).join(" · ");return `<div class="plan-line"><span class="status-icon">${icon}</span><span>${label}${when?` · ${esc(when)}`:""}</span>${attendeeAvatars(plan.attendeeIds)}</div>`}
function card(showItem,plan){return `<article class="show-card"><button class="card-main" data-edit-show="${showItem.id}"><div class="show-title">${esc(showItem.title)}</div>${plan?planLine(plan):""}</button><button class="secondary" data-edit-show="${showItem.id}">${plan?"Edit":"+ Add"}</button></article>`}
function empty(message){return `<div class="empty">${esc(message)}</div>`}

async function loadShows(){const response=await fetch("data/shows.json?v=20260809-2");if(!response.ok)throw new Error("Could not load the show catalogue.");const bytes=Number(response.headers.get("content-length"))||1;const reader=response.body?.getReader();let received=0,chunks=[],catalogue;if(reader){while(true){const {done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;const pct=Math.min(95,Math.round(received/bytes*100));$("loadProgress").textContent=`${pct}% · preparing shows`;await new Promise(requestAnimationFrame)}const all=new Uint8Array(received);let at=0;chunks.forEach(c=>{all.set(c,at);at+=c.length});catalogue=JSON.parse(new TextDecoder().decode(all)).shows}else catalogue=(await response.json()).shows;state.shows=canonicaliseCatalogue(catalogue);state.plans=canonicalisePlans(state.plans);persist(Boolean(remoteStore));$("loadProgress").textContent=`100% · ${state.shows.length.toLocaleString()} shows`;$("catalogCount").textContent=`${state.shows.length.toLocaleString()} shows`;$("loading").hidden=true;$("showResults").hidden=false;renderAll()}
function plansForShow(id){return state.plans.filter(p=>p.showId===id)}
function relevantPlan(showId,personId=state.currentPersonId){return plansForShow(showId).find(p=>p.attendeeIds.includes(personId))||plansForShow(showId)[0]}
function filteredShows(){const q=$("searchInput").value.trim().toLocaleLowerCase();return q?state.shows.filter(s=>s.title.toLocaleLowerCase().includes(q)):state.shows}
function renderShows(){const matches=filteredShows();$("showResults").innerHTML=matches.slice(0,state.visible).map(s=>card(s,relevantPlan(s.id))).join("")||empty("No matching shows");$("moreButton").hidden=matches.length<=state.visible;$("moreButton").textContent=`Show more · ${matches.length-state.visible} remaining`}
function renderMine(){const user=current();const plans=user?state.plans.filter(p=>p.attendeeIds.includes(user.id)):[];plans.sort((a,b)=>(a.date||"9999") .localeCompare(b.date||"9999")||(a.time||"").localeCompare(b.time||""));$("mineCount").textContent=`${plans.length} choices`;$("mineList").innerHTML=user?(plans.map(p=>card(show(p.showId),p)).join("")||empty("Nothing added yet")):empty("Choose who you are first")}
function renderToday(){const date=todayIso();$("todayDate").textContent=new Date(`${date}T12:00`).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"});const plans=state.plans.filter(p=>p.date===date&&effectiveStatus(p)!=="seen").sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99"));$("todayList").innerHTML=plans.map(p=>card(show(p.showId),p)).join("")||empty("No plans today")}
function renderDateStrip(){const dates=["all",...Array.from({length:29},(_,i)=>`2026-08-${String(i+3).padStart(2,"0")}`)];$("dateStrip").innerHTML=dates.map(d=>d==="all"?`<button class="date-pill ${state.selectedDate===d?"active":""}" data-date="all"><strong>All</strong>dates</button>`:`<button class="date-pill ${state.selectedDate===d?"active":""}" data-date="${d}"><strong>${new Date(`${d}T12:00`).toLocaleDateString("en-GB",{weekday:"short"})}</strong>${Number(d.slice(-2))}</button>`).join("")}
function dayHeading(date){if(date==="undated")return "No date yet";const label=new Date(`${date}T12:00`).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"});return date===todayIso()?`Today · ${label}`:label}
function daySection(date,plans){if(!plans.length)return empty("No group plans for this date");const ordered=[...plans].sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99"));return `<section class="day-section"><div class="day-heading"><h3>${esc(dayHeading(date))}</h3><span>${ordered.length} ${ordered.length===1?"plan":"plans"}</span></div><div class="card-list">${ordered.map(p=>card(show(p.showId),p)).join("")}</div></section>`}
function groupedDateSections(plans){const groups=new Map;for(const plan of plans){const key=plan.date||"undated",group=groups.get(key)||[];group.push(plan);groups.set(key,group)}return groups}
function renderGroup(){renderDateStrip();const plans=consolidatePlans(state.plans);if(state.selectedDate!=="all"){$("groupList").innerHTML=daySection(state.selectedDate,plans.filter(p=>p.date===state.selectedDate))}else{const groups=groupedDateSections(plans),today=todayIso(),upcoming=[...groups.keys()].filter(date=>date!=="undated"&&date>=today).sort(),past=[...groups.keys()].filter(date=>date!=="undated"&&date<today).sort().reverse();let html=upcoming.map(date=>daySection(date,groups.get(date))).join("");if(groups.has("undated"))html+=daySection("undated",groups.get("undated"));if(past.length){const count=past.reduce((sum,date)=>sum+groups.get(date).length,0);html+=`<details class="past-dates"><summary><span>Past dates</span><strong>${count} ${count===1?"plan":"plans"}</strong></summary><div class="past-date-sections">${past.map(date=>daySection(date,groups.get(date))).join("")}</div></details>`}$("groupList").innerHTML=html||empty("No dated group plans yet")}$("activityList").innerHTML=state.activity.slice(0,20).map(a=>`<div class="activity-item">${esc(a.text)} <small>· ${new Date(a.at).toLocaleString("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</small></div>`).join("")||empty("No activity yet")}
function renderPerson(){const p=current();$("personAvatar").textContent=p?.initials||"?";$("personAvatar").style.background=p?.colour||COLORS[0];$("personLabel").textContent=p?.name||"Choose person"}
function renderAll(){renderPerson();renderShows();renderMine();renderToday();renderGroup()}

function openPeople(){$("peoplePicker").innerHTML=state.people.map(p=>`<button type="button" class="person-row" data-person="${p.id}">${initials(p)}<span>${esc(p.name)}</span></button>`).join("");$("personDialog").showModal()}
function openPersonEditor(){let chosen=COLORS[state.people.length%COLORS.length];$("colourPicker").innerHTML=COLORS.map(c=>`<button type="button" class="colour-button ${c===chosen?"selected":""}" style="background:${c}" data-colour="${c}" aria-label="Choose ${c}"></button>`).join("");$("personForm").dataset.colour=chosen;$("personDialog").close();$("personEditor").showModal()}
function openPlan(showId){if(!current()){openPeople();return}const showItem=show(showId),existing=relevantPlan(showId);const form=$("planForm");form.reset();form.elements.showId.value=showId;$("planTitle").textContent=showItem.title;if(existing){form.elements.status.value=effectiveStatus(existing);form.elements.date.value=existing.date||"";form.elements.time.value=existing.time||"";form.dataset.planId=existing.id}else{delete form.dataset.planId;form.elements.status.value="interested"}const selected=new Set(existing?.attendeeIds||state.recentAttendees.length&&state.recentAttendees||[state.currentPersonId]);$("attendeePicker").innerHTML=state.people.map(p=>`<button type="button" class="attendee-chip ${selected.has(p.id)?"selected":""}" style="--chip:${p.colour}" data-attendee="${p.id}">${esc(p.initials)} · ${esc(p.name)}</button>`).join("");$("deletePlan").hidden=!existing;toggleDateFields();checkConflicts();$("planDialog").showModal()}
function selectedAttendees(){return [...document.querySelectorAll("#attendeePicker .selected")].map(b=>b.dataset.attendee)}
function toggleDateFields(){const value=$("planForm").elements.status.value;const needed=["dated","booked","seen"].includes(value);$("planForm").elements.date.closest("label").hidden=!needed;$("planForm").elements.time.closest("label").hidden=!needed}
function checkConflicts(){const f=$("planForm"),date=f.elements.date.value,time=f.elements.time.value,ids=selectedAttendees(),own=f.dataset.planId;if(!date||!time){$("conflictWarning").hidden=true;return}const minute=t=>Number(t.slice(0,2))*60+Number(t.slice(3));const clashes=state.plans.filter(p=>p.id!==own&&p.date===date&&p.time&&Math.abs(minute(p.time)-minute(time))<60&&p.attendeeIds.some(id=>ids.includes(id)));$("conflictWarning").hidden=!clashes.length;$("conflictWarning").textContent=clashes.length?`⚠ Possible conflict with ${clashes.map(p=>show(p.showId).title).join(", ")}.`:""}
function activity(text){state.activity.unshift({id:crypto.randomUUID(),text,at:new Date().toISOString()});state.activity=state.activity.slice(0,50)}
function savePlan(event){event.preventDefault();const f=event.currentTarget,ids=selectedAttendees();if(!ids.length){alert("Choose at least one attendee.");return}const status=f.elements.status.value,date=f.elements.date.value,time=f.elements.time.value;if(["dated","booked","seen"].includes(status)&&!date){alert("Choose a date.");return}if(time&&Number(time.slice(-1))%5!==0){alert("Times must end in 0 or 5.");return}const before=structuredClone(state.plans);let plan=state.plans.find(p=>p.id===f.dataset.planId);const data={showId:f.elements.showId.value,status,date:date||null,time:time||null,attendeeIds:ids,updatedAt:new Date().toISOString(),updatedBy:state.currentPersonId};if(plan)Object.assign(plan,data);else{plan={id:crypto.randomUUID(),...data};state.plans.push(plan)}state.recentAttendees=ids;activity(`${current().initials} ${status==="booked"?"booked":"updated"} ${show(data.showId).title} for ${ids.map(id=>person(id)?.initials).join(", ")}`);persist();$("planDialog").close();renderAll();offerUndo("Plan saved",before)}
function deletePlan(){const id=$("planForm").dataset.planId,before=structuredClone(state.plans),old=state.plans.find(p=>p.id===id);state.plans=state.plans.filter(p=>p.id!==id);activity(`${current().initials} removed ${show(old.showId).title}`);persist();$("planDialog").close();renderAll();offerUndo("Plan removed",before)}
let undoTimer;function offerUndo(text,before){state.undo=()=>{state.plans=before;persist();renderAll();hideSnack()};$("snackbarText").textContent=text;$("snackbar").classList.add("show");clearTimeout(undoTimer);undoTimer=setTimeout(hideSnack,5000)}function hideSnack(){$("snackbar").classList.remove("show");state.undo=null}

document.addEventListener("click",event=>{const edit=event.target.closest("[data-edit-show]");if(edit)openPlan(edit.dataset.editShow);const personButton=event.target.closest("[data-person]");if(personButton){state.currentPersonId=personButton.dataset.person;persist();$("personDialog").close();renderAll()}const attendee=event.target.closest("[data-attendee]");if(attendee){attendee.classList.toggle("selected");checkConflicts()}const date=event.target.closest("[data-date]");if(date){state.selectedDate=date.dataset.date;renderGroup()}const nav=event.target.closest("[data-view]");if(nav){state.view=nav.dataset.view;document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`${state.view}View`));document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b===nav));renderAll()}const colour=event.target.closest("[data-colour]");if(colour){document.querySelectorAll(".colour-button").forEach(b=>b.classList.toggle("selected",b===colour));$("personForm").dataset.colour=colour.dataset.colour}});
$("personButton").onclick=openPeople;$("addPersonButton").onclick=openPersonEditor;$("dialogAddPerson").onclick=openPersonEditor;$("searchInput").oninput=()=>{state.visible=40;renderShows()};$("moreButton").onclick=()=>{state.visible+=40;renderShows()};$("planForm").onsubmit=savePlan;$("deletePlan").onclick=deletePlan;$("undoButton").onclick=()=>state.undo?.();$("selectEveryone").onclick=()=>{document.querySelectorAll("#attendeePicker .attendee-chip").forEach(b=>b.classList.add("selected"));checkConflicts()};document.querySelectorAll(".close-dialog").forEach(b=>b.onclick=()=>b.closest("dialog").close());$("planForm").onchange=()=>{toggleDateFields();checkConflicts()};$("personForm").onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const p={id:crypto.randomUUID(),name:String(fd.get("name")).trim(),initials:String(fd.get("initials")).trim().toUpperCase(),colour:e.currentTarget.dataset.colour};state.people.push(p);state.currentPersonId=p.id;activity(`${p.initials} joined the group`);persist();e.currentTarget.reset();$("personEditor").close();renderAll()};

if(!state.currentPersonId&&state.people.length)state.currentPersonId=state.people[0].id;renderPerson();renderDateStrip();loadShows().catch(error=>{$("loading").innerHTML=`<strong>Could not load shows</strong><span>${esc(error.message)}</span>`});
connectFirebase(applyRemote,showSyncError).then(store=>{remoteStore=store;persist()}).catch(showSyncError);
